<?php

use Illuminate\Database\Seeder;

class NewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('news')->insert(
            [
            'title' => 'PN VietNam',
            'description' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'brief' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'image' => '1.jpg',
        ],
        [
            'title' => 'PN Campuchia',
            'description' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'brief' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'image' => '2.jpg',
        ],
        [
            'title' => 'PN Philipin',
            'description' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'brief' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'image' => '3.jpg',
        ],
        [
            'title' => 'PN',
            'description' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'brief' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'image' => '4.jpg',
        ],
        [
            'title' => 'PN',
            'description' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'brief' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'image' => '4.jpg',
        ],
        [
            'title' => 'PN',
            'description' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'brief' => '[GL] Gần đây, do hoạt động tái cơ cấu tổ chức, Natwest markets chúng tôi có 30 bức tranh đẹp nhưng không có không gian để sử dụng bởi văn phòng mới có diện tích nhỏ hơn rất nhiều. Những bức tranh này trước đây được trưng bày ở phòng hội nghị, phòng giám đốc cũng như lễ tân. Hầu hết những bức tranh này được vẽ bởi một họa sĩ người Việt nổi tiếng, ông Lê Thiết Cường, họa sĩ Jean-François Debongnie và một số họa sĩ nổi tiếng khác. Khi chúng tôi bắt đầu suy nghĩ về việc phải làm gì với những bức tranh này, điều chúng tôi nghĩ đến đầu tiên đấy là tặng cho các tổ chức từ thiện. Điều trùng hợp ngẫu nhiên đó là tôi đã gặp gỡ hai nhân vật rất thú vị, ông Phương Renaud, người điều hành của triễn làm nghệ thuật Việt NAM nổi tiếng ArtBlue Studio và ông Laurence Huret, thành viên Hội đồng Chủ tịch tổ chức Passerelles numériques. Điều đó giống như duyên số vậy, chúng tôi nhanh chóng nghĩ ra ý tưởng kết hợp với nhau với chủ đề “Việt nam” bởi hiện tại, tổ chức PN có cơ sở đào tạo tại 3 nước Châu Á, trong đó có Việt nam.',
            'image' => '4.jpg',
        ]
    );
    }
}
